### ISSUE TITLE
Not available in Package Control

### ISSUE THREAD

**Issue by pauljamesrussell** [beaknit/cform#6]
I notice this plugin isn't available in Package Control. Just wondered if you'd consider submitting it? A colleague recommended this plugin to me, but I'd have likely found it myself had it been in package control :smile:

Instructions for submitting packages are available [here][1].

[1]: https://sublime.wbond.net/docs/submitting_a_package

**Comment by beaknit** [comment]
Just submitted the pull request:  https://github.com/wbond/package_control_channel/pull/4282
